// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQhYdBJfQiW4po-03qwurJWbtdZtFQqzY',
    appId: '1:892365745976:web:e48ddb57443a6ddbef5bcd',
    messagingSenderId: '892365745976',
    projectId: 'auth-test-2c4ff',
    authDomain: 'auth-test-2c4ff.firebaseapp.com',
    storageBucket: 'auth-test-2c4ff.appspot.com',
    measurementId: 'G-4T3PCLHVHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1JLBI16gYtxYwUIZnalqLCfw5c5FdSIo',
    appId: '1:892365745976:android:e82596446b1fb52eef5bcd',
    messagingSenderId: '892365745976',
    projectId: 'auth-test-2c4ff',
    storageBucket: 'auth-test-2c4ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCal9fb_rkD91uEM5mqvSQyKbpmJeUx7Uc',
    appId: '1:892365745976:ios:00f0646eb2b6aaefef5bcd',
    messagingSenderId: '892365745976',
    projectId: 'auth-test-2c4ff',
    storageBucket: 'auth-test-2c4ff.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCal9fb_rkD91uEM5mqvSQyKbpmJeUx7Uc',
    appId: '1:892365745976:ios:00f0646eb2b6aaefef5bcd',
    messagingSenderId: '892365745976',
    projectId: 'auth-test-2c4ff',
    storageBucket: 'auth-test-2c4ff.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQhYdBJfQiW4po-03qwurJWbtdZtFQqzY',
    appId: '1:892365745976:web:f700f337d868007def5bcd',
    messagingSenderId: '892365745976',
    projectId: 'auth-test-2c4ff',
    authDomain: 'auth-test-2c4ff.firebaseapp.com',
    storageBucket: 'auth-test-2c4ff.appspot.com',
    measurementId: 'G-VE5RE6CLSY',
  );
}
